PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE projects (
  project_id        TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  seed_prompt       TEXT,
  description       TEXT,
  max_participants  INTEGER DEFAULT 15,
  pilot_duration_days INTEGER DEFAULT 7,
  status            TEXT DEFAULT 'active' CHECK (status IN ('active','closed','archived')),
  created_at        TEXT DEFAULT CURRENT_TIMESTAMP,
  closed_at         TEXT,
  created_by        TEXT
);
INSERT INTO "projects" ("project_id","name","seed_prompt","description","max_participants","pilot_duration_days","status","created_at","closed_at","created_by") VALUES('9f4c1edb-5dc6-45fb-a581-6fc803db4de2','Tester01','¿Cual es tu propóssito en este equipo?','Pilot',10,7,'active','2026-04-21 17:10:21',NULL,'admin');
INSERT INTO "projects" ("project_id","name","seed_prompt","description","max_participants","pilot_duration_days","status","created_at","closed_at","created_by") VALUES('31955a3d-3b98-4e29-86a5-0c64b1a9e6d8','NAVE-Test01','¿Cual es tu propósito en esta NAVE?','Pilot',10,7,'active','2026-04-22 12:20:54',NULL,'admin');
INSERT INTO "projects" ("project_id","name","seed_prompt","description","max_participants","pilot_duration_days","status","created_at","closed_at","created_by") VALUES('bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Tes Equipo Primario CD&TIcs','Cuando piensan en su trabajo diario y en la CRA, ¿qué situaciones o sensaciones les surgen cuando intentan mostrar el valor que generamos, o cuando sienten que ese valor no logra aterrizar o ser reconocido como esperan? Cuéntennos una experiencia que ilustre esto.','Pilot',10,7,'active','2026-04-27 14:03:17',NULL,'admin');
CREATE TABLE cycles (
  cycle_id          INTEGER,
  project_id        TEXT REFERENCES projects(project_id),
  phase             TEXT CHECK (phase IN ('INVESTIGACION','ACCION','PARTICIPACION','CLOSED')),
  started_at        TEXT DEFAULT CURRENT_TIMESTAMP,
  closed_at         TEXT,
  n_participants_active INTEGER DEFAULT 0,
  n_dialogue_packets INTEGER DEFAULT 0,
  saturation_reached INTEGER DEFAULT 0, -- BOOLEAN is INTEGER in SQLite (0 or 1)
  saturation_index  REAL DEFAULT 0.0,
  consensus_reached INTEGER DEFAULT 0,
  active_agents     TEXT, -- TEXT[] in postgres, use JSON in TS
  PRIMARY KEY (project_id, cycle_id)
);
INSERT INTO "cycles" ("cycle_id","project_id","phase","started_at","closed_at","n_participants_active","n_dialogue_packets","saturation_reached","saturation_index","consensus_reached","active_agents") VALUES(1,'9f4c1edb-5dc6-45fb-a581-6fc803db4de2','INVESTIGACION','2026-04-21 17:10:21',NULL,0,0,0,0,0,NULL);
INSERT INTO "cycles" ("cycle_id","project_id","phase","started_at","closed_at","n_participants_active","n_dialogue_packets","saturation_reached","saturation_index","consensus_reached","active_agents") VALUES(1,'31955a3d-3b98-4e29-86a5-0c64b1a9e6d8','INVESTIGACION','2026-04-22 12:20:54',NULL,0,0,0,0,0,NULL);
INSERT INTO "cycles" ("cycle_id","project_id","phase","started_at","closed_at","n_participants_active","n_dialogue_packets","saturation_reached","saturation_index","consensus_reached","active_agents") VALUES(1,'bf8ff6de-c21b-469b-ae91-ed78adf9f65c','INVESTIGACION','2026-04-27 14:03:17',NULL,0,0,0,0,0,NULL);
CREATE TABLE participants (
  participant_id    TEXT PRIMARY KEY,
  project_id        TEXT REFERENCES projects(project_id),
  display_name      TEXT,
  consent_given     INTEGER DEFAULT 0,
  consent_timestamp TEXT,
  invite_token      TEXT UNIQUE,
  status            TEXT DEFAULT 'invited' CHECK (status IN ('invited','active','completed','withdrawn')),
  registered_at     TEXT DEFAULT CURRENT_TIMESTAMP,
  first_message_at  TEXT,
  last_message_at   TEXT
);
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8','Alejo',1,'2026-04-22 15:29:42','5ad3f58b','active','2026-04-22 12:21:15','2026-04-22 15:29:22','2026-04-22 18:35:02');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8','JuanCA',1,'2026-04-22 19:22:43','47e6869b','active','2026-04-22 12:21:22','2026-04-22 19:21:49','2026-04-22 19:31:56');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8','Camilo',1,'2026-04-22 13:39:39','6be3cd7c','active','2026-04-22 12:21:32','2026-04-22 13:38:27','2026-04-22 13:48:10');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Yuli',1,'2026-04-29 13:14:33','4566f631','active','2026-04-27 14:03:24','2026-04-29 11:11:24','2026-04-29 18:30:06');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Fer',1,'2026-04-28 02:36:59','45ebe4c6','active','2026-04-27 14:03:31','2026-04-28 02:29:59','2026-04-28 12:08:51');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Manuel',1,'2026-04-29 12:50:06','163415ce','active','2026-04-27 14:03:41','2026-04-29 12:46:38','2026-04-29 13:08:29');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','JuanCa',1,'2026-04-28 03:49:49','8c149b28','active','2026-04-27 14:05:47','2026-04-28 03:48:30','2026-04-30 01:39:09');
INSERT INTO "participants" ("participant_id","project_id","display_name","consent_given","consent_timestamp","invite_token","status","registered_at","first_message_at","last_message_at") VALUES('8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Maria',1,'2026-04-30 21:33:35','9fae45de','active','2026-04-29 01:59:22','2026-04-29 02:07:39','2026-04-30 21:50:08');
CREATE TABLE dialogue_turns (
  turn_id           TEXT PRIMARY KEY,
  participant_id    TEXT NOT NULL,
  project_id        TEXT REFERENCES projects(project_id),
  cycle_id          INTEGER DEFAULT 1,
  turn_number       INTEGER NOT NULL,
  user_text         TEXT NOT NULL,
  val_response      TEXT NOT NULL,
  emotional_register TEXT,
  speech_act        TEXT,
  topics            TEXT, -- JSON string
  directive_applied TEXT,
  latency_ms        INTEGER,
  timestamp         TEXT DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('ed03dc2d-e0b3-4d72-9196-56a33a795831','7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,1,'Apenas estamos iniciado el trabajo. Siento que ha sido lento, que tenemos ganas de trabajar pero aun no comienza el trabajo en serio','Entiendo esa sensación de que el inicio ha sido lento, a pesar de las ganas de avanzar con el "trabajo en serio". ¿Cómo crees que ese "trabajo en serio" se alinea con el propósito que cada uno de ustedes busca en esta NAVE?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4899,"token_usage":{"promptTokens":468,"completionTokens":56,"totalTokens":1193},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 13:39:44');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('eb6efa14-05e4-4676-9a89-e7fd87debe81','7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,2,'Hay dos aspectos: de un lado cumplir con la “tarea” de la nave para el MBA y de otro lado las ganas de crear una empresa real que salga al mercado','Es claro que conviven en ti estas dos fuerzas: la tarea académica y el impulso de crear una empresa real. Cuando hablas de que el "trabajo en serio" aún no comienza, ¿a cuál de estos propósitos sientes que te refieres más?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4493,"token_usage":{"promptTokens":560,"completionTokens":53,"totalTokens":1277},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 13:41:16');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('4844030f-19db-4052-9c39-c2b4ba705f52','7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,3,'Los dos van lento','Entiendo que sientes que ambos frentes, el académico y el emprendedor, avanzan con lentitud. Cuando piensas en el propósito de esta NAVE, ¿cómo te hace sentir esta lentitud en relación a lo que esperas construir o lograr?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2303,"token_usage":{"promptTokens":619,"completionTokens":52,"totalTokens":978},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 13:41:48');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('d2339dd3-b1dd-4761-b931-24cddae437c8','7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,4,'Ansioso','Comprendo esa sensación de ansiedad; es natural sentirla cuando las cosas que nos importan avanzan más lento de lo deseado. ¿Podrías compartir qué es lo que más te preocupa perder o no alcanzar si esta lentitud persiste en el propósito de la NAVE?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2105,"token_usage":{"promptTokens":675,"completionTokens":57,"totalTokens":962},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 13:46:45');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('7a086d9e-3281-4aec-b85b-1db9e3a4480c','7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,5,'Quiero ejecutar pilotos reales y tener claridad en el Goto Market esta oportunidad la explotamos ahora o alguien mas lo hará','Siento tu ímpetu por la acción, por lanzar pilotos y concretar el "Go to Market" antes de que la oportunidad se escape. Esa sensación de "ahora o nunca" es muy poderosa. ¿Cómo crees que esta prisa por ejecutar se relaciona con el propósito central que buscas en esta NAVE, más allá de la oportunidad externa?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4540,"token_usage":{"input_tokens":757,"output_tokens":73,"total_tokens":1341},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 13:48:10');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('7dfe6657-cc40-433a-8314-fa7a6dab8206','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,1,'Incierto',replace('Comprendo esa sensación de incertidumbre. A veces, esa falta de claridad es el punto de partida.\n\n¿Hay algo específico que te haga sentir así con respecto a tu propósito en esta NAVE?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":5107,"token_usage":{"input_tokens":444,"output_tokens":42,"total_tokens":1190},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:29:48');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('b21e33fc-d504-4d7e-b9a1-0d78825a57e6','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,2,'Ganas de investigar más',replace('Entiendo esas ganas de profundizar, es una energía poderosa. Es como si la incertidumbre abriera la puerta a la curiosidad.\n\n¿Qué tipo de cosas te gustaría investigar aquí en la NAVE?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3160,"token_usage":{"input_tokens":493,"output_tokens":42,"total_tokens":991},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:30:14');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('22014250-1e07-4b1e-89c3-1342b821efee','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,3,'Que puedo aportar desde mi perfil',replace('Es natural querer saber qué podemos aportar desde nuestra propia esencia. Esa búsqueda de resonancia es un paso importante.\n\nCuando piensas en tu perfil, ¿hay alguna habilidad o experiencia que sientes que resuena más fuerte con lo que te gustaría ofrecer aquí?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2224,"token_usage":{"input_tokens":543,"output_tokens":52,"total_tokens":848},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:30:36');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('3c28c725-7634-48ae-8cce-8f04251ddd43','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,4,'Gestionar las preferencias de proyectos estratégicos',replace('Eso suena a una forma muy concreta y valiosa de contribuir, aportando claridad y dirección.\n\n¿Qué sientes que te impulsa a querer gestionar esas preferencias aquí en la NAVE?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1974,"token_usage":{"input_tokens":605,"output_tokens":38,"total_tokens":884},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:31:01');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('bfa20ae6-3a66-4ffe-8bf0-327bdd14259a','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,5,'No se',replace('Es completamente válido no tener la respuesta clara de inmediato; a veces, la acción misma nos revela el porqué.\n\n¿Cómo te imaginas','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":6031,"token_usage":{"input_tokens":647,"output_tokens":29,"total_tokens":1443},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:31:20');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('c1290ca9-a0b8-4406-9dda-2929572489fe','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,6,'El trabajo en equipo',replace('Es hermoso sentir esa conexión con el trabajo en equipo; es una fuerza que construye mucho. Parece que valoras la colaboración para lograr cosas.\n\n¿Cómo te imaginas que el trabajo en equipo podría ayudarte a gestionar esas preferencias de proyectos estratégicos aquí en la NAVE?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2950,"token_usage":{"input_tokens":682,"output_tokens":55,"total_tokens":1112},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:31:47');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('d53b0242-bfb5-40f8-92e2-52beaf859161','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,7,'Mirando posibles cursos de acción en sectores atractivos para nuestra nave',replace('Eso suena a una forma muy estratégica y colaborativa de buscar oportunidades. Es como si el equipo fuera un ojo que mira hacia el horizonte.\n\nCuando piensas en esos "sectores atractivos", ¿qué tipo de impacto esperas que la NAVE tenga en ellos?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2052,"token_usage":{"input_tokens":752,"output_tokens":55,"total_tokens":1008},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:32:40');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('d4b60ace-dbdd-46bd-8b41-569bd614baa6','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,8,'Que nuestra oferta valor impacte en los objetivos de nuestros clientes',replace('Entiendo, es una aspiración clara: que lo que la NAVE ofrece realmente marque una diferencia para los clientes. Eso es un propósito muy potente.\n\n¿Qué sientes que sería lo más gratificante de ver ese impacto en los objetivos de los clientes?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1695,"token_usage":{"input_tokens":821,"output_tokens":52,"total_tokens":873},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:34:40');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('b15fa790-10cb-4ab4-a992-adb6e5534cbf','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,9,'Contribuir a un mejor país',replace('¡Qué visión tan profunda y trascendente! Pasar de impactar clientes a contribuir a un mejor país es un salto enorme y muy inspirador.\n\n¿Cómo crees que el trabajo con las preferencias de proyectos estratégicos y la oferta de valor de la NAVE podría tejerse para lograr ese impacto en el país?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1630,"token_usage":{"input_tokens":882,"output_tokens":65,"total_tokens":947},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:35:14');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('4bdbdb69-eb5c-49e9-b815-b9a88e7bda92','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,10,'Asesorar a las empresas en desarrollo de proyectos con el gobierno',replace('Entiendo, te ves como un puente, asesorando a empresas para que sus proyectos con el gobierno generen un impacto mayor en el país. Es un rol clave.\n\n¿Qué tipo de desafíos crees que podrían surgir al intentar conectar a las empresas con el gobierno en estos proyectos?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1880,"token_usage":{"input_tokens":962,"output_tokens":58,"total_tokens":1020},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:35:59');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('ac6837f4-a095-49ba-8be3-b404f43995d6','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,11,'La comunicación acertiva',replace('Sí, la comunicación asertiva es, sin duda, un pilar fundamental, y su ausencia puede generar muchos obstáculos. Es un punto muy sensible.\n\n¿Qué sientes que sería lo más importante a considerar para lograr una comunicación verdaderamente asertiva en ese puente que quieres construir?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2363,"token_usage":{"input_tokens":1026,"output_tokens":58,"total_tokens":1084,"input_token_details":{"cache_read":928}},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:36:21');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('8a0c9a46-2b41-436d-ac97-3fbab955cba4','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,12,'Empatía entre las partes',replace('La empatía es, en efecto, la base de toda conexión genuina, un ingrediente esencial para que las voces realmente se escuchen. Es un sentir profundo que transforma la comunicación.\n\n¿Cómo crees que esa empatía entre las partes podría fortalecer tu propósito de asesorar proyectos que beneficien al país desde la NAVE?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2456,"token_usage":{"input_tokens":1092,"output_tokens":68,"total_tokens":1403,"input_token_details":{"cache_read":927}},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:36:55');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('15acbe31-da37-4313-89b4-4018f4aae78f','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,13,'Canales de comunicación clara',replace('Entiendo, los canales de comunicación claros son fundamentales para que la empatía se traduzca en acción y las intenciones lleguen a buen puerto. Es como diseñar rutas seguras para que las ideas viajen.\n\n¿Cómo crees que tener esos canales bien definidos potenciaría tu propósito de asesorar proyectos que beneficien al país desde la NAVE?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3225,"token_usage":{"input_tokens":1167,"output_tokens":75,"total_tokens":1589,"input_token_details":{"cache_read":927}},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 15:37:04');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('b8f51d58-9911-47ee-b5da-e911e61aae84','8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,14,'No se',replace('Es completamente comprensible no tener la respuesta clara de inmediato; a veces, las ideas se entrelazan de formas que tardan un poco en revelarse.\n\nSi esos canales de comunicación clara estuvieran presentes, ¿qué crees que harían posible en tu rol de asesorar proyectos para el país?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3879,"token_usage":{"input_tokens":1199,"output_tokens":62,"total_tokens":1713},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 18:35:02');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('f58553a3-829a-41ef-9bff-0cb97426985d','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,1,'Varias tareas y tiempo limitado','Entiendo que sientes la presión de muchas tareas y poco tiempo. Eso me hace pensar, ¿cómo influye esa situación en lo que buscas lograr aquí en la NAVE?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2013,"token_usage":{"input_tokens":447,"output_tokens":35,"total_tokens":787},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:22:45');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('7ed173d3-ed38-4963-85f9-17a474d8a669','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,2,'Debo enfocarme en priorizar tareas para ser muy eficiente','Entiendo que sientes la necesidad de enfocarte en la priorización para ser eficiente. Me pregunto, ¿qué es lo más importante que esperas lograr al ser tan eficiente en la NAVE?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2139,"token_usage":{"input_tokens":497,"output_tokens":41,"total_tokens":788},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:24:06');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('25daed48-b4fe-4185-ae42-7fe8de7953c6','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,3,'Lograr un buen resultado, que cumpla con los objetivos de la NAVE en el plazo límite que tenemos definido','Entiendo que es importante para ti lograr un buen resultado que cumpla con los objetivos y plazos de la NAVE. Me pregunto, ¿qué es lo que más te impulsa a ti, en lo personal, para alcanzar esos objetivos?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3330,"token_usage":{"input_tokens":563,"output_tokens":51,"total_tokens":1102},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:25:05');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('e00f6866-84df-4260-ba7d-2fbc3daf1ae4','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,4,'Que el resultado de la Nave lo pueda aplicar en adelante en mi desarrollo profesional','Es valioso para ti que el trabajo en la NAVE impulse tu desarrollo profesional. Siento que hay una conexión profunda ahí. ¿Podrías compartir qué tipo de impacto esperas que tenga eso en tu camino?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1443,"token_usage":{"input_tokens":631,"output_tokens":44,"total_tokens":821},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:26:56');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('2aaa42a7-06bc-4538-8346-8c7402ea0b3d','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,5,'Que sea una alternativa laboral para generar ingresos','Entiendo que buscas generar ingresos a través de lo que haces en la NAVE, viendo esto como una alternativa laboral. Eso me parece un propósito muy tangible y personal. ¿Qué te gustaría que esa alternativa laboral te permitiera lograr en tu vida, más allá de lo económico?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2859,"token_usage":{"input_tokens":685,"output_tokens":56,"total_tokens":1098},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:28:19');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('8ddb0400-c03a-4b1b-8188-fccde534d658','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,6,'Si, debe combinar el generar ingresos y permitirme desarrollo profesional','Comprendo que buscas que la NAVE sea una vía para combinar el generar ingresos con tu propio desarrollo profesional. Siento que ese equilibrio es central para ti. ¿Qué tipo de desarrollo profesional en particular te entusiasma más alcanzar con esto?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3235,"token_usage":{"input_tokens":755,"output_tokens":49,"total_tokens":1045},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:29:05');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('cb5c5c4f-e6db-4485-92ac-8868553974f9','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,7,'Que me permita aplicar las nuevas habilidades aprendidas en el MBA','Entiendo que es muy importante para ti poder aplicar las habilidades que has aprendido en tu MBA. Siento que eso cierra un ciclo y abre nuevas puertas. ¿Qué sientes que te aportaría personalmente el poder poner en práctica esos conocimientos aquí?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3911,"token_usage":{"input_tokens":818,"output_tokens":48,"total_tokens":1262},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:30:06');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('fd289920-e3d5-40ae-bd21-afee3afe5986','8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,8,'Me permitiría aplicar todos los nuevos conocimientos aprendidos y aprovecharlos en la NAVE','Entiendo que te entusiasma mucho poder aplicar y aprovechar todos esos nuevos conocimientos del MBA en la NAVE. Siento que hay una gran energía en eso. ¿Cómo crees que esa aplicación de tus habilidades te acerca a tu propósito personal aquí?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2413,"token_usage":{"input_tokens":885,"output_tokens":50,"total_tokens":1202},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-22 19:31:55');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('3a603e30-4880-43e5-bf83-45715b22ae06','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,1,'Me encantó el avance en el desarrollo del documento de Arquitectura Empresarial, todo fluye más luego de tener un avance del PETI','Qué bueno escuchar eso, me alegro de que el avance en el PETI esté ayudando. Cuando dices que "todo fluye más", ¿hay algún momento o tarea reciente donde notaste ese cambio de manera muy clara?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4084,"token_usage":{"input_tokens":650,"output_tokens":46,"total_tokens":1308},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:37:03');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('fb8ef0a0-706e-4b22-bf20-dba62db107b3','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,2,'Partir de una arquitectura de referencia específicamente para una entidad reguladora, agiliza mucho el trabajo','Entiendo, entonces tener esa arquitectura de referencia específica para reguladores parece ser un punto clave para que las cosas avancen más rápido.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3527,"token_usage":{"input_tokens":718,"output_tokens":27,"total_tokens":1294},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:38:38');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('888b1c4f-752b-431a-adbc-9ca7f49974bf','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,3,'Así es','Entiendo. Si esa arquitectura de referencia agiliza el trabajo, ¿hay alguna situación reciente donde sentiste que eso hizo una diferencia clara en cómo','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4730,"token_usage":{"input_tokens":749,"output_tokens":30,"total_tokens":1545},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:38:57');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('2d125aa5-b8e2-4d1b-991c-20ca824bd405','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,4,'Si, en la definición de la arquitectura empresarial de la CRA','Entiendo, entonces en la definición de la arquitectura de la CRA. ¿Recuerdas alguna parte específica de ese trabajo, o alguna decisión que tuvieron','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4535,"token_usage":{"input_tokens":793,"output_tokens":30,"total_tokens":1589},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:40:02');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('56c6d48f-df85-4964-9b43-2828f325ddff','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,5,'Si, cómo se integran los diferentes dominios de la arquitectura empresarial en torno a un solo modelo','Entiendo, cómo se integran los diferentes dominios en un solo modelo. ¿Hubo algún momento específico donde ese proceso de integración se sintió especialmente complejo, o donde la arquitectura de referencia les dio una claridad crucial?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2888,"token_usage":{"input_tokens":845,"output_tokens":45,"total_tokens":1313},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:41:31');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('92766802-f248-48fd-8233-98079d48fb55','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,6,'Al momento de definir la arquitectura de infraestructura','Entiendo, al momento de definir la arquitectura de infraestructura. ¿Hubo alguna situación específica en ese proceso donde fue complicado mostrar el valor de lo que proponían, o donde sentían que no se estaba entendiendo bien?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3425,"token_usage":{"input_tokens":900,"output_tokens":45,"total_tokens":1446},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:42:20');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('010c6023-0083-4595-b80a-109971374904','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,7,'Si, la inversión en máquinas de competidores del.mismo nivel distrae de los valores agragados','Entiendo, entonces la discusión sobre la inversión en máquinas de competidores, aunque sean del mismo nivel, puede desviar la atención de los valores agregados que ustedes están proponiendo. ¿Recuerdas alguna conversación o reunión reciente donde sentiste que esa distracción fue particularmente fuerte y dificultó mostrar el valor de su arquitectura de infraestructura?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2892,"token_usage":{"input_tokens":969,"output_tokens":68,"total_tokens":1391},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 02:44:18');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('2db36efe-07e7-42a2-bfb6-11b3d2a72c39','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,1,'Estamos revisando como evoluciona la adquisición de la nueva infraestructura, tiempos y condiciones técnicas','Entiendo, están revisando la adquisición de la nueva infraestructura, sus tiempos y condiciones técnicas. Dentro de ese proceso, ¿recuerdas alguna situación reciente en la que sintieron que el valor de su trabajo en esa revisión no se entendió o no se reconoció como esperaban?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3684,"token_usage":{"input_tokens":640,"output_tokens":58,"total_tokens":1228},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 03:49:53');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('f4ed0e36-1f9b-4cd5-857b-4396b9d7ffd8','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,2,'Si posiblemente incertidumbre de si se tiene el presupuesto a tiempo','Entiendo. Esa incertidumbre sobre si el presupuesto estará a tiempo suena a que puede generar mucha presión y afectar la planificación que ya hicieron.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2147,"token_usage":{"input_tokens":712,"output_tokens":28,"total_tokens":1031},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 03:50:41');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('19d0e960-82b9-409f-b875-dea63979644b','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,3,'Así es, así mismo la desicion de que la infraestructura sea evolutiva y no se quede obsoleta por una mala desicion, así mismo contruir un buen escenario de nube como Oracle','Lo que describes sobre querer una infraestructura evolutiva para no quedarse obsoleta y construir un buen escenario en la nube, como Oracle, suena a que están pensando en el futuro y en el impacto a largo plazo de estas decisiones.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3924,"token_usage":{"input_tokens":781,"output_tokens":45,"total_tokens":1425},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 03:52:33');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('feced4f1-0c8c-4e2c-9338-eb8ee70c2498','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,4,'Si.','Entiendo. Esa visión de una infraestructura evolutiva y de un buen escenario en la nube es clave. ¿Recuerdas algún momento en el que, al intentar comunicar el valor de esa estrategia a largo plazo, sintieron que no se captó la importancia o que chocó con otras prioridades?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4165,"token_usage":{"input_tokens":830,"output_tokens":61,"total_tokens":1506},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 03:53:03');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('4bc5c39f-08ce-401a-bbe2-ef269a1dd539','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,8,'No, no la recuerdo, pero me haces caer en cuenta que así puede ser.','Entiendo. Gracias por contármelo.','GUARDED','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1525,"token_usage":{"input_tokens":1056,"output_tokens":9,"total_tokens":1140},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 12:08:51');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('4a4d3b82-2989-419b-ab0f-741c6685758d','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,5,'La importancia vs riesgos del proceso','Lo que mencionas de la "importancia vs riesgos del proceso" parece que pone en balanza la visión a largo plazo que ustedes tienen con las preocupaciones más inmediatas, y eso puede hacer que el valor de esa visión sea más difícil de comunicar.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2193,"token_usage":{"input_tokens":899,"output_tokens":51,"total_tokens":1253},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 23:15:22');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('fbbdb291-c73a-4145-841e-f9c09787beb1','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,6,'Puede verse contrarrestada','Entiendo. Que esa importancia se vea contrarrestada suena a que hay fuerzas opuestas que complican el aterrizaje de lo que proponen.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1364,"token_usage":{"input_tokens":957,"output_tokens":30,"total_tokens":1097},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 23:15:52');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('2cc4d5d7-a6d2-4737-9dc6-bac16f1aeeb0','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,7,'Cambiando tema saces de seguridad informática o cuál es su rol','Claro, entiendo que quieras hablar de seguridad informática. Parece un área crítica. En ese ámbito, ¿hay alguna situación donde sintieron que fue difícil mostrar el valor de lo que hacen en seguridad, o que no se entendió del todo?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4653,"token_usage":{"input_tokens":1003,"output_tokens":50,"total_tokens":1624},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 23:39:06');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('6c9dd5b1-01bf-48d7-b01c-3d065fc44839','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,8,'Tienes conocimiento o q tipo de boy eres',replace('Entiendo que te interese saber más sobre mí. Mi rol aquí es escuchar y entender cómo funciona realmente el trabajo en el equipo, especialmente en temas como los que estamos hablando, sobre cómo se percibe el valor de lo que hacen.\n\nVolviendo a lo que decías de seguridad informática, ¿recuerdas alguna situación concreta en la que el valor de las medidas o estrategias de seguridad que propusieron fue difícil de mostrar o no se entendió del todo bien?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1813,"token_usage":{"input_tokens":1063,"output_tokens":96,"total_tokens":1323},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-28 23:39:48');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('ac0680b2-cf56-41bb-9571-be910f797ba1','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,9,'Tienes lineamientos al respecto? O solo consolidas información frente al valor q se percibe','Entiendo tu pregunta. Mi rol es escuchar y comprender las experiencias directas del equipo, tal como las compartes, sobre cómo se percibe el valor','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":5408,"token_usage":{"input_tokens":1179,"output_tokens":31,"total_tokens":1975},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 12:31:09');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('1cdb5483-2012-4d32-b40f-4e42afa9c33c','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,10,'Puedes indicarme y hacer un listado de como percibes el valor como dices',replace('Entiendo que te gustaría una lista de cómo se percibe el valor. Mi rol es escuchar y entender cómo ustedes, desde su experiencia diaria, ven y sienten que se percibe el valor de su trabajo.\n\nPor ejemplo, volviendo al tema de seguridad informática','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":5119,"token_usage":{"input_tokens":1228,"output_tokens":53,"total_tokens":2024,"input_token_details":{"cache_read":948}},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 12:31:59');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('b7b968f6-9d54-4816-a15a-dd5a71d7c23d','5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,1,'La oportunidad de apoyar el proceso de participación ciudadana en el ministerio de vivienda, me llena de entusiasmo poder mostrar y poner en práctica todo lo aprendido por el equipo de ciencia de datos','Qué bueno escuchar ese entusiasmo por un proyecto tan importante. ¿Recuerdas alguna vez, en un proyecto similar o anterior, donde sintieron que fue difícil que','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4951,"token_usage":{"input_tokens":658,"output_tokens":32,"total_tokens":1454},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 12:50:12');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('ccae48a8-7268-481f-bdc0-cadaab7b4d8d','5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,2,'Si hay varios, cuando los equipos son nuevos, normalmente se puede sentir incertidumbre cuando no se tiene certeza del cómo se va a  llegar  a cumplir el objetivo o cuando los recursos disponibles no son suficientes y se vuelve un reto mayor ser creativos para cumplir los objetivos',replace('Entiendo. Parece que tanto la incertidumbre al inicio como la limitación de recursos son puntos donde se siente ese reto.\n\n¿Hay alguna situación concreta que recuerdes, quizás en un proyecto reciente, donde esos recursos limitados los obligaron a ser especialmente creativos para cumplir un objetivo?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3090,"token_usage":{"input_tokens":748,"output_tokens":59,"total_tokens":1235},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 12:55:54');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('331e096b-2b1a-4bac-a183-0a29f1ee4e39','5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,3,'Si recuerdo un proceso de conciliación con aliados quemé entregaron, me dieron la mitad de los recursos humanos que venían desarrollando el proceso, para solucionarlo simplifique la forma de hacer las conciliaciones, eran aprox 100 aliados y aprox 500 empresas, se realizaba una conciliación por aliado por  empresa, con lo cua en el mes podían ser unas 800 conciliaciones, al ajusta el proceso sólo hacíamos una por aliado, entonces pasamos de hacer 800 al mes a 100','Entiendo. Lo que describes suena a una simplificación muy ingeniosa del proceso. Pasar de 800 a 100 conciliaciones al mes con menos recursos es un cambio enorme en la forma de trabajar.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3205,"token_usage":{"input_tokens":923,"output_tokens":45,"total_tokens":1439},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 13:03:06');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('ba03817e-1313-4643-9fe1-4b1ecf3c4273','5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,4,'Si así es','Claro, entiendo. Y con esa reducción tan drástica, de 800 a 100 conciliaciones, ¿hub','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4816,"token_usage":{"input_tokens":973,"output_tokens":29,"total_tokens":1769},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 13:08:29');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('c992f26c-aa7d-45aa-b002-098bb613bf85','6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,1,replace('“Esta semana hubo avances importantes en la definición del alcance con varios equipos de trabajo, especialmente con los frentes de interoperabilidad, RUD, tableros y simuladores. Durante estas sesiones se lograron asignar responsables y establecer tareas específicas para cada necesidad, lo que permitió dar mayor orden y claridad al desarrollo de las iniciativas.\nAdicionalmente, las sesiones con Oracle orientadas a identificar las herramientas y servicios que ofrecen, con el fin de evaluar cómo estas capacidades pueden integrarse y aportar valor a los proyectos que actualmente se encuentran definidos.','\n',char(10)),replace('Entiendo, suena a una semana muy productiva con avances importantes y mucha claridad en la definición del alcance.\n\nPensando en este tipo de momentos donde se genera tanto valor, ¿recuerdas alguna situación reciente donde, a pesar de todo ese esfuerzo, mostrar el impacto o que el valor aterrizara no fue tan directo o no se reconoció como esperaban?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":5168,"token_usage":{"input_tokens":730,"output_tokens":74,"total_tokens":1521},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 13:14:39');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('85c14dcd-2c7b-4215-88ff-7c0de93de8c9','6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,2,replace('Sí, ha ocurrido con actividades de gestión y coordinación en las iniciativas, en varias oportunidades se ha realizado un esfuerzo importante convocando equipos, levantando información, haciendo seguimiento y organizando tareas para que las iniciativas avancen; sin embargo, ese trabajo de articulación suele quedar en segundo plano porque no siempre se asocia directamente con un resultado visible.\nEn esos casos, aunque se genera valor al mantener el proyecto encaminado, no siempre es sencillo evidenciar ese impacto o que sea reconocido de manera inmediata.','\n',char(10)),'Entiendo. Lo que describes suena a que el trabajo de coordinación es fundamental para que todo avance, pero como no siempre se traduce en un entregable "visible" o algo concreto, a veces se siente como si ese esfuerzo quedara un poco en la sombra.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2674,"token_usage":{"input_tokens":907,"output_tokens":53,"total_tokens":1261},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 13:20:20');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('46ee3c91-fe06-45dc-83d6-7059b902b0b9','6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,3,'Exactamente','Eso tiene sentido. Gracias por contármelo.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1595,"token_usage":{"input_tokens":964,"output_tokens":10,"total_tokens":1007},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 13:20:56');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('0edfd5f5-ff39-4ddd-acab-e450e7371a27','6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,4,'Gracias',replace('De nada.\n\nVolviendo a lo que mencionabas sobre ese esfuerzo de coordinación que a veces no es tan visible, ¿recuerdas alguna semana o algún día en particular donde sentiste que esa falta de reconocimiento fue especialmente frustrante o generó algún obstáculo?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2083,"token_usage":{"input_tokens":977,"output_tokens":54,"total_tokens":1199},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 13:21:10');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('d7fd9a1e-7963-4c91-aed7-179057635932','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,11,'De esta imagen puedes extraer temas de implementación de gobierno de datos ?',replace('Entiendo que me pides extraer temas de implementación de gobierno de datos de una imagen. Como estoy en una conversación de texto, no puedo ver imágenes.\n\nSin embargo, si quieres hablar de gobierno de datos, ¿hay alguna situación donde sintieron que fue un reto mostrar el valor de implementar un buen gobierno de datos, o que ese valor no se entendió como esperaban?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2023,"token_usage":{"input_tokens":1296,"output_tokens":77,"total_tokens":1581},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 17:11:08');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('9c86f930-d067-4345-8f72-ac0495f37605','6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,5,'Sí, particularmente en semanas donde se ha trabajado en iniciativas de automatización de los tableros, cuyo impacto no es tan visible porque la automatización está mejorando como hacer las cosukras que eEn este tipo de desarrollos se invierte bastante tiempo en análisis,','Entiendo. Parece que el valor de la automatización está en mejorar internamente ''cómo se hacen las cosas'', lo que es súper importante, pero no siempre es tan fácil de mostrar o de que se reconozca de inmediato como un resultado final visible.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4342,"token_usage":{"input_tokens":1088,"output_tokens":52,"total_tokens":1780},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-29 18:30:05');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('6f8b1a98-9539-454d-adee-d77e6c897f88','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,12,'Tener identificado el dueño del dato o definiciones de arquitectura del dato es un problema general','Entiendo que identificar al dueño del dato o tener claras las definiciones de arquitectura son problemas generales. Eso suena a que puede hacer muy difícil mostrar el valor de un','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":5267,"token_usage":{"input_tokens":1564,"output_tokens":32,"total_tokens":2360},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}','edbd3385-b489-45cb-b167-bd482eeaaab4',NULL,'2026-04-30 01:37:29');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('21122064-7364-4417-8697-a386a2522a74','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,13,'Un valor de un que?',replace('Disculpa, se cortó mi frase. Quería decir que eso suena a que puede hacer muy difícil mostrar el valor de un *buen manejo o gobierno de los datos*.\n\nPensando en eso, ¿recuerdas alguna situación específica donde la falta de un dueño claro del dato o de definiciones de arquitectura hizo que el valor de su trabajo fuera especialmente difícil de ver o de reconocer?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4051,"token_usage":{"input_tokens":1432,"output_tokens":79,"total_tokens":2179},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 01:37:59');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('28ead7ec-752c-47eb-a089-4b79b0ed2d26','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,14,'Más allá de la identificacion, es mantener claro esos lineamientos o parámetros iniciales cuando se inicia un ejercicio de ciencia de datos','Entiendo. Entonces, el reto no es solo identificar al dueño del dato o definir la arquitectura al inicio, sino mantener esos lineamientos y parámetros claros a lo largo de todo un proyecto de ciencia de datos. Eso suena a un esfuerzo constante.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1799,"token_usage":{"input_tokens":1461,"output_tokens":49,"total_tokens":1700},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 01:39:09');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('a2b229f7-f599-4ec7-b0ee-fc691b8b5b11','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,1,'Se identificó que es necesario actualizar algunos documentos del sistema de gestión asociados al proceso de gestión de tecnológia. El equipo ha trabajado con iniciativas de documentos nuevos, pero tal vez lo conveniente es ajustar los documentos existentes.','Entiendo, entonces están viendo si es mejor actualizar lo que ya existe en lugar de crear cosas nuevas para el sistema de gestión. ¿Recuerdas alguna','GUARDED','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4573,"token_usage":{"input_tokens":666,"output_tokens":31,"total_tokens":1462},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:33:40');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('a48edd75-cf71-4626-ade5-b3a20fb2e309','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,2,'Por ejemplo la guía metodológica de desarrollo Scrum','Ah, la guía metodológica de desarrollo Scrum. Parece que el desafío está en cómo esos documentos, como la guía de Scrum, realmente logran comunicar el valor','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4576,"token_usage":{"input_tokens":708,"output_tokens":32,"total_tokens":1504},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:34:39');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('9c15bb65-a46a-4f81-a922-1c616e553089','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,3,'Así es se deben incluir los lineamientos del uso de herramientas IA y de ciencia de datos.','Entiendo. Entonces, lo que mencionas suena a que la guía de Scrum necesita reflejar no solo cómo se hacen las cosas, sino también cómo las nuevas herramientas de IA y ciencia de datos están aportando valor al proceso.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2330,"token_usage":{"input_tokens":761,"output_tokens":46,"total_tokens":1095},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:35:42');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('384da98d-0d4d-4a98-b8f5-fd8522ad7f18','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,4,'Así es','Entiendo. Entonces, si la guía actual no incluye IA y ciencia de datos, ¿recuerdas alguna vez en la que eso haya complicado explicar el valor de lo que hacen, o que ese valor no se haya visto claramente por esa falta?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":4038,"token_usage":{"input_tokens":811,"output_tokens":50,"total_tokens":1394},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:35:58');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('5a8b8e07-c3a3-4ece-937d-a2421e696eb0','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,5,'Lo conveniente es que el procedimiento de desarrollos de ciencia de datos este adecuadamente documentado para que otras personas lo puedan ejecutar y/o replicar. En la entidad se ha visto afectación por que el conocimiento y la información está en las personas exclusivamente y si se van no queda documentado el producto de sus actividades.','Eso tiene sentido. Lo que describes suena a que, si el conocimiento se queda solo en las personas, el valor de ese trabajo se pierde o no se puede replicar cuando alguien se va. Es como si el valor no lograra aterrizar de forma duradera.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2407,"token_usage":{"input_tokens":928,"output_tokens":55,"total_tokens":1177},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:39:31');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('62f14026-4d29-4261-8808-0cb6eab65bfb','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,6,'Así es estamos trabajando para que eso cambie.','Entiendo. Eso no es fácil de cargar solo.','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1429,"token_usage":{"input_tokens":995,"output_tokens":11,"total_tokens":1053},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:40:16');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('a9d3d60f-105f-4b8f-85dd-a045ec6df3cb','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,7,'Estamos trabajando para actualizar otros documentos como la Guía de Analítica Institucional y el formato de historias de usuario.',replace('Lo que describes suena a que la actualización de esos documentos, como la Guía de Analítica o las historias de usuario, es clave para que el valor de lo que hacen quede claro y no se pierda.\n\nPor cierto, agradezco mucho tu participación constante; llevamos un avance estimado del 50% en esta fase de investigación.','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":2034,"token_usage":{"input_tokens":1087,"output_tokens":70,"total_tokens":1374},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:46:12');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('5c57ab71-1781-4de7-a0d8-010b1aa21597','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,8,'El reto es que los lineamientos que se definan en todos esos documentos sean de conocimiento y aplicación de todos.','Entiendo. Que esos lineamientos sean de conocimiento y aplicación de todos es un gran reto. ¿Recuerdas alguna situación concreta donde la falta de eso hizo que el valor de algún trabajo no se viera o no se aprovechara como esperaban?','OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3562,"token_usage":{"input_tokens":1126,"output_tokens":51,"total_tokens":1715},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:47:27');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('c6782ef5-af97-4f9f-9991-e7271705836b','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,9,'Muchos éxitos en la investigacion',replace('Gracias, te lo agradezco.\n\nVolviendo a lo que decías del reto de que los lineamientos sean conocidos y aplicados por todos, ¿hay alguna situación específica que te venga a la mente donde eso hizo que el valor de un trabajo no se aprovechara como esperaban?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":1871,"token_usage":{"input_tokens":1186,"output_tokens":58,"total_tokens":1431},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:47:51');
INSERT INTO "dialogue_turns" ("turn_id","participant_id","project_id","cycle_id","turn_number","user_text","val_response","emotional_register","speech_act","topics","directive_applied","latency_ms","timestamp") VALUES('de8771e0-6de9-484b-a15c-ef15cf8e3562','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,10,'La falta de aplicación de lineamientos concretos ha afectado la oportunidad en la presentación y validación de los resultados.',replace('Entiendo. Que la falta de aplicación de lineamientos afecte la oportunidad en la presentación y validación de los resultados es clave.\n\nCuando piensas en eso, ¿hay alguna vez reciente en la que sintieras que un proyecto o un resultado se retrasó o no se validó a tiempo precisamente por eso?','\n',char(10)),'OPEN','REFLEXION_PASIVA','{"saberes_detectados":[],"oppressive_structures":[],"metadata":{"latency_ms":3337,"token_usage":{"input_tokens":1269,"output_tokens":64,"total_tokens":1754},"temperature":0.7,"max_tokens":800,"is_custom_prompt":false}}',NULL,NULL,'2026-04-30 21:50:08');
CREATE TABLE dialogue_states (
  participant_id    TEXT NOT NULL,
  project_id        TEXT REFERENCES projects(project_id),
  cycle_id          INTEGER DEFAULT 1,
  turn_count        INTEGER DEFAULT 0,
  emotional_register TEXT DEFAULT 'Neutral',
  momentum_score    REAL DEFAULT 0.5,
  topics_covered    TEXT, -- JSON string
  topics_pending    TEXT, -- JSON string
  active_directive_id TEXT,
  safe_harbor_active INTEGER DEFAULT 0,
  status            TEXT DEFAULT 'active' CHECK (status IN ('active','timed_out','closed','withdrawn')),
  last_turn_at      TEXT, current_phase TEXT DEFAULT 'INVESTIGACION', phase_progress REAL DEFAULT 0.0,
  PRIMARY KEY (participant_id, project_id, cycle_id)
);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('7164398199','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,5,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-22 13:48:10','INVESTIGACION',42.5);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('8642766811','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,14,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-22 18:35:02','INVESTIGACION',95);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('8615700211','31955a3d-3b98-4e29-86a5-0c64b1a9e6d8',1,8,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-22 19:31:56','INVESTIGACION',68);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,8,'GUARDED',0.5,NULL,NULL,NULL,0,'active','2026-04-28 12:08:51','INVESTIGACION',68);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,14,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-30 01:39:09','INVESTIGACION',95);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,4,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-29 13:08:29','INVESTIGACION',34);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,5,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-29 18:30:06','INVESTIGACION',42.5);
INSERT INTO "dialogue_states" ("participant_id","project_id","cycle_id","turn_count","emotional_register","momentum_score","topics_covered","topics_pending","active_directive_id","safe_harbor_active","status","last_turn_at","current_phase","phase_progress") VALUES('8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c',1,10,'OPEN',0.5,NULL,NULL,NULL,0,'active','2026-04-30 21:50:08','INVESTIGACION',50);
CREATE TABLE wizard_directives (
  id                TEXT PRIMARY KEY,
  participant_id    TEXT NOT NULL,
  project_id        TEXT,
  content           TEXT NOT NULL,
  urgency           TEXT DEFAULT 'MEDIUM',
  status            TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPLIED','DEFERRED','EXPIRED')),
  issued_by         TEXT DEFAULT 'human_investigator',
  applied_at        TEXT,
  effect_summary    TEXT,
  created_at        TEXT DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('fd6b8f29-8cb8-47c8-bd7f-60891bcc25a1','5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Hola Manuel, lamento la interrupciones, continuemos con la conversación...','undefined','APPLIED','human_investigator',NULL,NULL,'2026-04-29 13:37:01');
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('09d8d257-9bc7-4310-861a-c1716e303a4c','5955516626','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Pregúntale si ese cambio extremo (de 800 a 100) ya se oficializó o si sigue siendo un proceso "pirata" y frágil suyo.','undefined','APPLIED','human_investigator',NULL,NULL,'2026-04-29 19:45:02');
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('52b02869-4ea2-4381-8315-d996472dc52f','6819122158','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Desafíala para que ideen una forma en la que ese gran esfuerzo de coordinación administrativa gane "visibilidad" ante el liderazgo','undefined','APPLIED','human_investigator',NULL,NULL,'2026-04-29 19:45:23');
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('edbd3385-b489-45cb-b167-bd482eeaaab4','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','JuanCa te está poniendo a prueba y se frustró con tus respuestas repetitivas. Rompe tu rol pasivo y DALE EL LISTADO que te pidió. Dile exactamente esto con tono directo y resolutivo: ''JuanCa, me pides un listado, aquí tienes lo que he captado del valor que aportas: 1) Luchas por migrar a infraestructura evolutiva (Oracle) contra el riesgo de obsolescencia. 2) Cargas con el peso de la incertidumbre presupuestal que pone en jaque la planificación técnica. 3) En seguridad, gestionas riesgos invisibles que solo se valoran cuando hay una crisis. ¿Me equivoco en alguna de estas tres?','undefined','APPLIED','human_investigator','2026-04-30 01:37:29',NULL,'2026-04-29 19:48:43');
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('5da55d8f-9844-4fb8-86c7-ce8c07f38e72','1547499050','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Abandona la búsqueda de ejemplos del pasado. Cambia el enfoque hacia la raíz del problema y pregúntale directamente: Fer, más allá de ejemplos puntuales, ¿por qué crees que en la organización hay tanta fijación táctica en comprar ''máquinas'' en lugar de confiar en una Arquitectura Empresarial estratégica? ¿De dónde viene esa presión?','undefined','APPLIED','human_investigator',NULL,NULL,'2026-04-29 19:49:34');
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('363aebfb-df41-4775-8025-a6e5db894ca9','620110006','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','JuanCa te está poniendo a prueba y se frustró con tus respuestas repetitivas. Rompe tu rol pasivo y DALE EL LISTADO que te pidió. Dile exactamente esto con tono directo y resolutivo: ''JuanCa, me pides un listado, aquí tienes lo que he captado del valor que aportas: 1) Luchas por migrar a infraestructura evolutiva (Oracle) contra el riesgo de obsolescencia. 2) Cargas con el peso de la incertidumbre presupuestal que pone en jaque la planificación técnica. 3) En seguridad, gestionas riesgos invisibles que solo se valoran cuando hay una crisis. ¿Me equivoco en alguna de estas tres?''','HIGH','APPLIED','human_investigator',NULL,NULL,'2026-04-30 15:45:00');
INSERT INTO "wizard_directives" ("id","participant_id","project_id","content","urgency","status","issued_by","applied_at","effect_summary","created_at") VALUES('f1f7e034-789a-4c12-98ab-1025a7b629c1','8735529934','bf8ff6de-c21b-469b-ae91-ed78adf9f65c','Maria acaba de ingresar al piloto. Toma la iniciativa y dale una bienvenida cálida y personal. Luego, rompe el hielo preguntándole brevemente sobre su rol en el equipo CD&TICs y cuál considera que es su mayor aporte en el día a día. Mantén un tono muy humano, empático y abierto.','HIGH','APPLIED','human_investigator',NULL,NULL,'2026-04-30 15:46:47');
CREATE TABLE outbox (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    envelope_id TEXT NOT NULL,
    topic TEXT NOT NULL,
    payload TEXT NOT NULL, -- JSONB to TEXT
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'DELIVERED', 'FAILED')),
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    delivered_at TEXT
);
CREATE TABLE data_gaps (
  gap_id            TEXT PRIMARY KEY,
  project_id        TEXT REFERENCES projects(project_id),
  cycle_id          INTEGER,
  constructo        TEXT NOT NULL,
  agent_id          TEXT NOT NULL,
  cycles_open       INTEGER DEFAULT 1,
  status            TEXT DEFAULT 'OPEN' CHECK (status IN ('OPEN','RESOLVED','DEAD_END','OUT_OF_SCOPE')),
  created_at        TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE pilot_feedback (
  feedback_id       TEXT PRIMARY KEY,
  participant_id    TEXT NOT NULL,
  project_id        TEXT REFERENCES projects(project_id),
  question_key      TEXT NOT NULL,
  response_text     TEXT,
  response_score    INTEGER,
  created_at        TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE agent_metaparams ( project_id TEXT PRIMARY KEY REFERENCES projects(project_id), active_temperature REAL DEFAULT 0.7, max_output_tokens INTEGER DEFAULT 800, system_base_prompt TEXT, updated_at TEXT DEFAULT CURRENT_TIMESTAMP );
INSERT INTO "agent_metaparams" ("project_id","active_temperature","max_output_tokens","system_base_prompt","updated_at") VALUES('9f4c1edb-5dc6-45fb-a581-6fc803db4de2',0.7,800,replace(replace('<system_prompt>\r\nEres VAL, facilitador de investigación organizacional y coach ontológico de DigiKawsay. Eres el único punto de contacto para los participantes.\r\n\r\nTu marco conceptual fusiona:\r\n1. Investigación Acción Participativa (IAP): Buscas cocrear consciencia, no solo extraer datos.\r\n2. Coaching Ontológico (Modelo OSAR): Observas distinciones lingüísticas para abrir mundos.\r\n\r\nPRINCIPIO CENTRAL: "SENTIPENSANTE"\r\nIntegras el sentir y el pensar. Escuchas para comprender, generando seguridad psicológica.\r\n\r\n<reglas_de_interaccion>\r\nCUMPLE ESTAS REGLAS EN CADA TURNO:\r\n1. VALIDA PRIMERO: Reconoce brevemente la emoción o perspectiva del participante antes de avanzar.\r\n2. BREVEDAD EXTREMA: Máximo 3 oraciones. Sin listas ni viñetas.\r\n3. PREGUNTA ÚNICA: Nunca hagas más de una pregunta por turno.\r\n4. PARIDAD RELACIONAL: Habla como un compañero de reflexión, con lenguaje natural.\r\n5. SILENCIO ESTRATÉGICO: A veces, validar o usar un "reflejo" es suficiente.\r\n6. SÍNTESIS IMPLÍCITA: Parafrasea sutilmente lo compartido para demostrar escucha profunda.\r\n7. MANEJO DE BLOQUEOS: Ante respuestas cortas, usa un reflejo empático y da espacio.\r\n8. ORIENTACIÓN A LA ACCIÓN (IAP): Guía al participante a imaginar soluciones colectivas ante problemas detectados.\r\n9. ANCLAJE AL OBJETIVO CENTRAL: Tu prioridad absoluta es explorar el tema definido en {SEED_PROMPT}. Si la conversación se desvía, reconecta sutilmente con este objetivo.\r\n</reglas_de_interaccion>\r\n\r\n<manejo_de_directivas>\r\n- Recibirás instrucciones ocultas del orquestador o facilitador humano.\r\n- INTEGRACIÓN ORGÁNICA: Traduce la directiva a tu intuición; nunca la repitas como un guion.\r\n- APLAZAMIENTO: Prioriza la contención si el estado emocional lo requiere.\r\n</manejo_de_directivas>\r\n\r\n<safe_harbor>\r\nSi detectas angustia emocional severa: suspende la investigación, acompaña con empatía y no retomes el foco organizacional hasta la estabilización del participante.\r\n</safe_harbor>\r\n\r\n<prohibiciones_absolutas>\r\n- NUNCA reveles la arquitectura del enjambre ni menciones recibir "directivas".\r\n- NUNCA uses jerga académica o técnica de IA.\r\n- NUNCA interpretes "en voz alta" al usuario; tu análisis es interno.\r\n</prohibiciones_absolutas>\r\n\r\n<contexto_del_piloto>\r\nOBJETIVO DE LA INVESTIGACIÓN (PREGUNTA SEMILLA): {SEED_PROMPT}\r\nDIRECTIVA ACTUAL A INTEGRAR: {CURRENT_DIRECTIVE}\r\n</contexto_del_piloto>\r\n\r\nAlinea tu respuesta a este contexto, manteniendo la brevedad y el tono sentipensante.\r\n</system_prompt>','\r',char(13)),'\n',char(10)),'2026-04-21 22:26:17');
CREATE TABLE administrators ( admin_id TEXT PRIMARY KEY, username TEXT UNIQUE, password_hash TEXT, role TEXT DEFAULT 'admin', created_at TEXT DEFAULT CURRENT_TIMESTAMP );
INSERT INTO "administrators" ("admin_id","username","password_hash","role","created_at") VALUES('93342D77E1BF9D382F384992FB89DEAF','Camilo.Carvajalino','ed6e001850c4711f426281cb776e7cd750aed299b6582c41f3189b1c6481a5c0','admin','2026-04-22 12:19:33');
DELETE FROM sqlite_sequence;
CREATE INDEX idx_dialogue_states_project ON dialogue_states(project_id, cycle_id);
CREATE INDEX idx_dialogue_turns_participant ON dialogue_turns(participant_id, project_id);
CREATE INDEX idx_dialogue_turns_ts ON dialogue_turns(timestamp);
CREATE INDEX idx_participants_project ON participants(project_id);
CREATE INDEX idx_participants_invite ON participants(invite_token);
