// Each challenge defines a scientific scenario with two disjunctive resolution paths.
// pathA = simpler operation (lower energy efficiency)
// pathB = complex operation (higher energy efficiency, preferred mastery signal)

export const BIOMES = {
  DOME:    'dome',     // Cúpula Geodésica — suma / resta
  ORBITAL: 'orbital', // Invernadero Orbital — multiplicación
  FLUID:   'fluid',   // Laboratorio de Fluidos — división
}

export const MATH_CHALLENGES = [
  {
    id: 'ch-001',
    biome: BIOMES.DOME,
    title: 'Reparación de Paneles Solares',
    narrative:
      'La tormenta magnética dañó 7 paneles hoy y 5 paneles ayer. El sistema de energía necesita saber el total para calibrar el generador de respaldo.',
    sample: { icon: '⚡', label: 'Paneles dañados', value: '? unidades' },
    pathA: {
      label: 'Contar uno a uno',
      operation: 'addition',
      expression: '7 + 5',
      answer: 12,
      energyCost: 8,
      efficiencyLabel: 'Eficiencia Media',
      hint: 'Suma los paneles de cada día.',
    },
    pathB: {
      label: 'Registro acumulativo',
      operation: 'addition_with_grouping',
      expression: '(7 + 3) + 2',
      answer: 12,
      energyCost: 3,
      efficiencyLabel: 'Eficiencia Alta',
      hint: 'Agrupa primero para llegar a 10 y luego suma el resto.',
    },
    correctAnswer: 12,
    tags: ['suma', 'agrupación'],
  },
  {
    id: 'ch-002',
    biome: BIOMES.DOME,
    title: 'Calibración del Escudo Térmico',
    narrative:
      'La temperatura exterior es −18 °C. El escudo necesita elevarla 23 grados para estabilizar el módulo. ¿Cuál será la temperatura final?',
    sample: { icon: '🌡️', label: 'Temperatura objetivo', value: '? °C' },
    pathA: {
      label: 'Termómetro lineal',
      operation: 'addition',
      expression: '-18 + 23',
      answer: 5,
      energyCost: 9,
      efficiencyLabel: 'Eficiencia Media',
      hint: 'Avanza de −18 sumando 23 pasos.',
    },
    pathB: {
      label: 'Salto a cero y proyección',
      operation: 'subtraction_complement',
      expression: '23 − 18',
      answer: 5,
      energyCost: 4,
      efficiencyLabel: 'Eficiencia Alta',
      hint: 'Sube 18 grados para llegar a 0, luego proyecta los 5 restantes.',
    },
    correctAnswer: 5,
    tags: ['resta', 'números negativos'],
  },
  {
    id: 'ch-003',
    biome: BIOMES.ORBITAL,
    title: 'Siembra en la Cámara de Cultivo',
    narrative:
      'Necesitas plantar 6 filas de tomates espaciales con 8 plantas cada una. El sistema de riego automático requiere el total exacto para distribuir el agua.',
    sample: { icon: '🌱', label: 'Plantas totales', value: '? plantas' },
    pathA: {
      label: 'Suma repetida',
      operation: 'repeated_addition',
      expression: '8+8+8+8+8+8',
      answer: 48,
      energyCost: 12,
      efficiencyLabel: 'Eficiencia Baja',
      hint: 'Suma 8 seis veces seguidas.',
    },
    pathB: {
      label: 'Matriz de cultivo',
      operation: 'multiplication',
      expression: '6 × 8',
      answer: 48,
      energyCost: 2,
      efficiencyLabel: 'Eficiencia Alta',
      hint: 'Filas por columnas = total en un solo cálculo.',
    },
    correctAnswer: 48,
    tags: ['multiplicación', 'suma repetida'],
  },
  {
    id: 'ch-004',
    biome: BIOMES.ORBITAL,
    title: 'Carga de Módulos de Energía',
    narrative:
      'Cada dron puede transportar 9 módulos de energía. La base central envía 5 drones en misión. ¿Cuántos módulos llegan en total?',
    sample: { icon: '🚁', label: 'Módulos transportados', value: '? módulos' },
    pathA: {
      label: 'Conteo por dron',
      operation: 'repeated_addition',
      expression: '9+9+9+9+9',
      answer: 45,
      energyCost: 10,
      efficiencyLabel: 'Eficiencia Media',
      hint: 'Cuenta los módulos de cada dron uno a uno.',
    },
    pathB: {
      label: 'Protocolo de flota',
      operation: 'multiplication',
      expression: '5 × 9',
      answer: 45,
      energyCost: 2,
      efficiencyLabel: 'Eficiencia Alta',
      hint: 'Drones × módulos por dron = carga total.',
    },
    correctAnswer: 45,
    tags: ['multiplicación', 'resolución de problemas'],
  },
  {
    id: 'ch-005',
    biome: BIOMES.FLUID,
    title: 'Distribución del Combustible Criogénico',
    narrative:
      'El depósito contiene 72 litros de combustible criogénico. Debes llenarlo en 9 contenedores idénticos para el lanzamiento. ¿Cuántos litros por contenedor?',
    sample: { icon: '🧪', label: 'Litros por contenedor', value: '? L' },
    pathA: {
      label: 'Resta sucesiva',
      operation: 'repeated_subtraction',
      expression: '72−8−8−8−8−8−8−8−8−8',
      answer: 8,
      energyCost: 14,
      efficiencyLabel: 'Eficiencia Baja',
      hint: 'Resta 8 litros nueve veces hasta vaciar el depósito.',
    },
    pathB: {
      label: 'Partición exacta',
      operation: 'division',
      expression: '72 ÷ 9',
      answer: 8,
      energyCost: 2,
      efficiencyLabel: 'Eficiencia Alta',
      hint: 'Divide el total entre los contenedores disponibles.',
    },
    correctAnswer: 8,
    tags: ['división', 'resta repetida'],
  },
]

export const BIOME_META = {
  [BIOMES.DOME]: {
    id: BIOMES.DOME,
    name: 'Cúpula Geodésica',
    subtitle: 'Sector +  −',
    icon: '🔷',
    colorClass: 'biome-dome',
    accentColor: '#00f5ff',
    bgFrom: 'from-blue-950',
    bgTo: 'to-cyan-950',
    borderColor: 'border-cyan-500',
    glowColor: 'shadow-cyan-500/40',
    description: 'Restaura el flujo de energía resolviendo operaciones de suma y resta.',
    challenges: ['ch-001', 'ch-002'],
  },
  [BIOMES.ORBITAL]: {
    id: BIOMES.ORBITAL,
    name: 'Invernadero Orbital',
    subtitle: 'Sector ×',
    icon: '🌿',
    colorClass: 'biome-orbital',
    accentColor: '#39ff14',
    bgFrom: 'from-green-950',
    bgTo: 'to-emerald-950',
    borderColor: 'border-green-500',
    glowColor: 'shadow-green-500/40',
    description: 'Optimiza los cultivos espaciales dominando la multiplicación.',
    challenges: ['ch-003', 'ch-004'],
  },
  [BIOMES.FLUID]: {
    id: BIOMES.FLUID,
    name: 'Laboratorio de Fluidos',
    subtitle: 'Sector ÷',
    icon: '🧬',
    colorClass: 'biome-fluid',
    accentColor: '#ffbe00',
    bgFrom: 'from-purple-950',
    bgTo: 'to-pink-950',
    borderColor: 'border-amber-500',
    glowColor: 'shadow-amber-500/40',
    description: 'Calibra los fluidos criogénicos particionando con precisión.',
    challenges: ['ch-005'],
  },
}
